name: make-python-rpm

resources:
  repositories:
    - repository: ansible
      type: github
      name: sede-x/netops-ansible
      endpoint: sede-x
      ref: main

trigger:
  batch: true
  branches:
    include:
    - main

pool: 'tetoolingpool'

parameters:
- name: RUN_SONAR
  displayName: Run SonarQube code analysis
  type: boolean
  default : true

variables:
  run_sonar: ${{ parameters.RUN_SONAR }}

steps:
- checkout: self
  path: s/make-python-rpm
- checkout: ansible
  path: s/ansible

- template: azure-pipelines-templates/sonar-template.yml@ansible
  parameters:
     projectKey: 'com.shell.netops-make-python-rpm'
     projectName: 'netops-make-python-rpm'
     projectBaseDir: './make-python-rpm'

